var dinner = [
  {
    key: "B00OSTKBDA",
    category: "dinner",
    name: "Salmon with Graperfruit and Lentil Salad",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Dinner/dinner6.png",
    description: "How we dream about our future",
    price: 9.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBDB",
    category: "dinner",
    name: "Lemony Salmon Piccata",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Dinner/dinner2.png",
    description: "How we dream about our future",
    price: 10.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBDC",
    category: "dinner",
    name: "Pork Tenderloin With Quinoa Pilaf",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Dinner/dinner5.png",
    description: "How we dream about our future",
    price: 11.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBDD",
    category: "dinner",
    name: "French fries with cheese",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Dinner/dinner4.png",
    description: "How we dream about our future",
    price: 8.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBDE",
    category: "dinner",
    name: "Garlic Butter Baked Salmon",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Dinner/dinner3.png",
    description: "How we dream about our future",
    price: 6.99,
    shipping: 15.99,
  },

  {
    key: "B00OSTKBDF",
    category: "dinner",
    name: "Baked Chiken",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Dinner/dinner1.png",
    description: "How we dream about our future",
    price: 9.99,
    shipping: 3.99,
  },
];
console.log();
export default dinner;
