var breakfast = [
  {
    key: "B00OSTKBFA",
    category: "breakfast",
    name: "Eggs Benedict",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Breakfast/breakfast1.png",
    price: 8.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBFB",
    category: "breakfast",
    name: "Breakfast sandwich",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Breakfast/breakfast2.png",
    price: 9.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBFC",
    category: "breakfast",
    name: "Baked Chiken",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Breakfast/breakfast3.png",
    price: 10.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBFD",
    category: "breakfast",
    name: "Bagel and cream cheese",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Breakfast/breakfast4.png",
    price: 6.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBFE",
    category: "breakfast",
    name: "Full Breakfast Fried Egg Toast Brunch",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Breakfast/breakfast5.png",
    price: 3.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBFF",
    category: "breakfast",
    name: "Toast Croissant Fried egg",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../Breakfast/breakfast6.png",
    price: 8.99,
    shipping: 3.99,
  },
];

export default breakfast;
