var launch = [
  {
    key: "B00OSTKBLA",
    category: "lunch",
    name: "Healthy Meal Plan",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../lunch/lunch6.png",
    description: "How we dream about our future",
    price: 23.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBLB",
    category: "lunch",
    name: "Fried Chicken Bento",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../lunch/lunch5.png",
    description: "How we dream about our future",
    price: 9.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBLC",
    category: "lunch",
    name: "Tarragon-Rubbed-Salmon",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../lunch/lunch3.png.png",
    description: "How we dream about our future",
    price: 10.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBLD",
    category: "lunch",
    name: "Bangladeshi Lunch",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../lunch/lunch4.png",
    description: "How we dream about our future",
    price: 8.99,
    shipping: 3.99,
  },

  {
    key: "B00OSTKBLE",
    category: "lunch",
    name: "Beef Steak",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../lunch/lunch1.png",
    description: "How we dream about our future",
    price: 3.99,
    shipping: 15.99,
  },

  {
    key: "B00OSTKBLF",
    category: "lunch",
    name: "Honey-Soy-Glazed Salmon with Peppers",
    seller: "RCA",
    wholePrice: "57",
    priceFraction: "99",
    stock: 96,
    star: 3,
    starCount: 620,
    img: "../lunch/lunch2.png",
    description: "How we dream about our future",
    price: 7.99,
    shipping: 3.99,
  },
];
export default launch;
